// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IHeroiconsOutlineBadgeCheck: typeof import('~icons/heroicons-outline/badge-check')['default']
    ILineMdGithub: typeof import('~icons/line-md/github')['default']
    ILineMdGithubLoop: typeof import('~icons/line-md/github-loop')['default']
    ILineMdLightbulb: typeof import('~icons/line-md/lightbulb')['default']
    ILineMdMoon: typeof import('~icons/line-md/moon')['default']
    ILineMdMoonTwotone: typeof import('~icons/line-md/moon-twotone')['default']
    ILineMdSunnyOutline: typeof import('~icons/line-md/sunny-outline')['default']
    ILineMdSunnyOutlineLoop: typeof import('~icons/line-md/sunny-outline-loop')['default']
    ILogosGithubIcon: typeof import('~icons/logos/github-icon')['default']
    ILogosTypescriptIcon: typeof import('~icons/logos/typescript-icon')['default']
    ILogosVitejs: typeof import('~icons/logos/vitejs')['default']
    ILogosWebpack: typeof import('~icons/logos/webpack')['default']
    IVscodeIconsFileTypeVue: typeof import('~icons/vscode-icons/file-type-vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
